(defun pr (val) (format t "~%--> ~s~%~%" val))
(defun matches (seq1 seq2)
    (cond ((or (null seq1) (null seq2)) T)
        ((or (null (car seq1)) (null (car seq2)))
            (matches (cdr seq1) (cdr seq2)))
        ((equal (car seq1) (car seq2)) (matches (cdr seq1)(cdr seq2)))
        (t NIL)))
(pr (matches nil '(1 2 3)))
(pr (matches '(1 2 3) '(1 2 3)))
(pr (matches '(1 2 4) '(1 2 3)))
(pr (matches '(1 NIL 3) '(1 2 3)))
(pr (matches '(1 2) '(1 2 3)))
(defvar *events* '(((28 2) "Geburtstag Peter")((12 6)"Geburtstag Maria") ((24 12) "Weihnachten") ((28)"Miete überweisen") ((1 3 2012)"Zahnarzt")))
(defun next-n-days (n) '(((0) 26 2 2012) ((1) 27 2 2012) ((2) 28 2 2012) ((3) 29 2 2012) ((4) 1 3 2012)))
(pr (next-n-days 5))
(defun events-on-date (date events)
    (remove-if-not #'(lambda (event) (matches (cdr date) (car event))) events))
(defun events-next-n-days (days events)
    (apply #'append (mapcar #'(lambda (date) 
            (mapcar #'(lambda (event) (cons (caar date) (cdr event))) 
                (events-on-date date events))) 
        (next-n-days days))))
(pr (events-on-date '((2) 28 2 2012) *events*))
(pr (events-next-n-days 5 *events*))